apiVersion: yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: example-ybcluster
  namespace: default
spec:
  replicationFactor: 3
  master:
    replicas: 3
    resources:
      limits:
        cpu: 0.5
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 2Gi
    storage:
      size: 10Gi
  tserver:
    replicas: 3
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
    storage:
      count: 1
      size: 10Gi
